# Generated by Django 4.2.5 on 2023-09-25 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_id',
            new_name='id',
        ),
    ]
